# The r-universe registry draft is generated by data-raw/harvest.R, which
# is not part of the installed package. These tests run from a source
# checkout (including the harvest workflow gate) and skip during R CMD
# check of the built tarball.

registry_path <- test_path("..", "..", "data-raw", "packages.json")

test_that("packages.json always carries washr and owdata", {
  skip_if(!file.exists(registry_path), "data-raw/packages.json not present (built tarball)")
  reg <- jsonlite::fromJSON(registry_path)
  expect_true(all(c("package", "url") %in% names(reg)))
  # The custom registry supersedes the auto-generated CRAN registry, so
  # washr must never be missing (openwashdata/owdata#8), and owdata
  # should list itself.
  expect_true(all(c("washr", "owdata") %in% reg$package))
  expect_false(any(duplicated(reg$package)))
  expect_true(all(grepl("^https://github\\.com/openwashdata/", reg$url)))
})

test_that("packages.json covers every package in the catalog", {
  skip_if(!file.exists(registry_path), "data-raw/packages.json not present (built tarball)")
  reg <- jsonlite::fromJSON(registry_path)
  expect_true(all(owd_packages()$pkg_name %in% reg$package))
})
